site_name: "Aeiva: An Evolving Intelligent Virtual Assistant"
site_url: https://aeiva.ai/
repo_url: https://github.com/chatsci/Aeiva


plugins:
- search
- autorefs
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          show_source: false

nav:
  - Home: index.md
  - Get Started:
    - Introduction: intro.md
    # - Roadmap: ROADMAP.md
    # - Coding guidelines: coding_guidelines.md
  - Tutorials: 
    - How to automatically generate documentation from docstrings: tutorials/generate_docs.md
    # - Install MineDojo on Mac with M1 chip: tutorials/install_minedojo.md
  # - How-To Guides: how-to-guides.md
  - API References: reference.md
  # - Explanations: explanation.md
  - Blogs:
    - Thoughts on key concepts for agentic intelligence: blogs/Thoughts_on_key_concepts_for_agentic_intelligence.md


theme:
  name: "material"
  logo: assets/logo.png
  custom_dir: docs/overrides-material/
  features:
    - navigation.tabs
    