"""Shared constants for browser service orchestration."""

DEFAULT_FILL_STEP_TIMEOUT_MS = 5_000
DEFAULT_SNAPSHOT_RESOLVE_TIMEOUT_MS = 1_500
DEFAULT_SNAPSHOT_RESOLVE_LIMIT = 200
DEFAULT_SCROLL_RECOVERY_CLICK_TIMEOUT_MS = 3_000
DEFAULT_FIELD_TARGET_LOCK_USES = 3
DEFAULT_SCROLL_REPEAT_LIMIT = 4
DEFAULT_SCROLL_REQUEST_WINDOW_SECONDS = 8.0
DEFAULT_SCROLL_NO_PROGRESS_TRIGGER = 2
