project_root_dir: /Users/bangliu/Documents/ChatSCI/Aeiva/
data_root_dir: /Users/bangliu/Documents/ChatSCI/Aeiva/datasets/
model_root_dir: /Users/bangliu/Documents/ChatSCI/Aeiva/pretrained_models/

datasets:
  alpaca:
    alpaca_data.json: /Users/bangliu/Documents/ChatSCI/Aeiva/datasets/alpaca/alpaca_data.json
  avsd:
    avsd_train.json: /Users/bangliu/Documents/ChatSCI/Aeiva/datasets/avsd/avsd_train.json
  vqa:
    v2_mscoco_train2014_annotations.json: /Users/bangliu/Documents/ChatSCI/Aeiva/datasets/vqa/v2_mscoco_train2014_annotations.json
    v2_OpenEnded_mscoco_train2014_questions.json: /Users/bangliu/Documents/ChatSCI/Aeiva/datasets/vqa/v2_OpenEnded_mscoco_train2014_questions.json
  macaw:
    generated_examples_coco.json: /Users/bangliu/Documents/ChatSCI/Aeiva/datasets/macaw/generated_examples_coco.json
    generated_examples_avsd.json: /Users/bangliu/Documents/ChatSCI/Aeiva/datasets/macaw/generated_examples_avsd.json

models:
  macaw:
    tokenizer: /Users/bangliu/Documents/ChatSCI/Aeiva/pretrained_models/macaw/
    model: /Users/bangliu/Documents/ChatSCI/Aeiva/pretrained_models/macaw/
  whisper:
    model: /Users/bangliu/Documents/ChatSCI/Aeiva/pretrained_models/whisper/
  llama7b:
    model: /Users/bangliu/Documents/ChatSCI/Aeiva/pretrained_models/llama7b/
  clip:
    model: /Users/bangliu/Documents/ChatSCI/Aeiva/pretrained_models/clip/
  